<?php

namespace Container2J8x8aG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationvolService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AakxYK3.App\Entity\Reservationvol' shared service.
     *
     * @return \App\Entity\Reservationvol
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AakxYK3": it references class "App\\Entity\\Reservationvol" but no such service exists.');
    }
}
