<?php

namespace ContainerCxOCKmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YOdyGPKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.yOdyGPK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yOdyGPK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\AdminAccountController::edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminDashboardController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\AdminUserController::DisableOrEnableUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\AdminUserController::add' => ['privates', '.service_locator.jwZ0ULN', 'get_ServiceLocator_JwZ0ULNService', true],
            'App\\Controller\\AdminUserController::delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\AdminUserController::edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\AdminUserController::index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\AdminUserController::show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator._gDwqM0', 'get_ServiceLocator_GDwqM0Service', true],
            'App\\Controller\\UserController::generatePdf' => ['privates', '.service_locator.tJdcSXe', 'get_ServiceLocator_TJdcSXeService', true],
            'App\\Controller\\UserController::index' => ['privates', '.service_locator.m_0T5T.', 'get_ServiceLocator_M0T5T_Service', true],
            'App\\Controller\\UserController::resetpassword' => ['privates', '.service_locator.j1CM4JT', 'get_ServiceLocator_J1CM4JTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\AdminAccountController:edit' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\AdminDashboardController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\AdminUserController:DisableOrEnableUser' => ['privates', '.service_locator.GQZbvNR', 'get_ServiceLocator_GQZbvNRService', true],
            'App\\Controller\\AdminUserController:add' => ['privates', '.service_locator.jwZ0ULN', 'get_ServiceLocator_JwZ0ULNService', true],
            'App\\Controller\\AdminUserController:delete' => ['privates', '.service_locator.GPGtF8v', 'get_ServiceLocator_GPGtF8vService', true],
            'App\\Controller\\AdminUserController:edit' => ['privates', '.service_locator.9uW928t', 'get_ServiceLocator_9uW928tService', true],
            'App\\Controller\\AdminUserController:index' => ['privates', '.service_locator.Q1F27w5', 'get_ServiceLocator_Q1F27w5Service', true],
            'App\\Controller\\AdminUserController:show' => ['privates', '.service_locator.4T4EJFR', 'get_ServiceLocator_4T4EJFRService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.iQAD6w2', 'get_ServiceLocator_IQAD6w2Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator._gDwqM0', 'get_ServiceLocator_GDwqM0Service', true],
            'App\\Controller\\UserController:generatePdf' => ['privates', '.service_locator.tJdcSXe', 'get_ServiceLocator_TJdcSXeService', true],
            'App\\Controller\\UserController:index' => ['privates', '.service_locator.m_0T5T.', 'get_ServiceLocator_M0T5T_Service', true],
            'App\\Controller\\UserController:resetpassword' => ['privates', '.service_locator.j1CM4JT', 'get_ServiceLocator_J1CM4JTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\AdminAccountController::edit' => '?',
            'App\\Controller\\AdminDashboardController::index' => '?',
            'App\\Controller\\AdminUserController::DisableOrEnableUser' => '?',
            'App\\Controller\\AdminUserController::add' => '?',
            'App\\Controller\\AdminUserController::delete' => '?',
            'App\\Controller\\AdminUserController::edit' => '?',
            'App\\Controller\\AdminUserController::index' => '?',
            'App\\Controller\\AdminUserController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\UserController::generatePdf' => '?',
            'App\\Controller\\UserController::index' => '?',
            'App\\Controller\\UserController::resetpassword' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\AdminAccountController:edit' => '?',
            'App\\Controller\\AdminDashboardController:index' => '?',
            'App\\Controller\\AdminUserController:DisableOrEnableUser' => '?',
            'App\\Controller\\AdminUserController:add' => '?',
            'App\\Controller\\AdminUserController:delete' => '?',
            'App\\Controller\\AdminUserController:edit' => '?',
            'App\\Controller\\AdminUserController:index' => '?',
            'App\\Controller\\AdminUserController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\UserController:generatePdf' => '?',
            'App\\Controller\\UserController:index' => '?',
            'App\\Controller\\UserController:resetpassword' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
