<?php

namespace ContainerCxOCKmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TJdcSXeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tJdcSXe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tJdcSXe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'formBuilder' => ['privates', '.errored..service_locator.tJdcSXe.Symfony\\Component\\Form\\FormBuilderInterface', NULL, 'Cannot autowire service ".service_locator.tJdcSXe": it references interface "Symfony\\Component\\Form\\FormBuilderInterface" but no such service exists. Did you create a class that implements this interface?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'formBuilder' => 'Symfony\\Component\\Form\\FormBuilderInterface',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
