<?php

namespace ContainerCxOCKmq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormBuilderInterfaceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tJdcSXe.Symfony\Component\Form\FormBuilderInterface' shared service.
     *
     * @return \Symfony\Component\Form\FormBuilderInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.tJdcSXe": it references interface "Symfony\\Component\\Form\\FormBuilderInterface" but no such service exists. Did you create a class that implements this interface?');
    }
}
