<?php

namespace ContainerTzFRMLM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Zkc3GnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._zkc3Gn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._zkc3Gn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'vol' => ['privates', '.errored..service_locator._zkc3Gn.App\\Entity\\Vol', NULL, 'Cannot autowire service ".service_locator._zkc3Gn": it references class "App\\Entity\\Vol" but no such service exists.'],
        ], [
            'vol' => 'App\\Entity\\Vol',
        ]);
    }
}
