<?php

namespace ContainerTzFRMLM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZpxPtMLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zpxPtML' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zpxPtML'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationVoyage' => ['privates', '.errored..service_locator.zpxPtML.App\\Entity\\ReservationVoyage', NULL, 'Cannot autowire service ".service_locator.zpxPtML": it references class "App\\Entity\\ReservationVoyage" but no such service exists.'],
        ], [
            'reservationVoyage' => 'App\\Entity\\ReservationVoyage',
        ]);
    }
}
