<?php

namespace ContainerTzFRMLM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProgrammeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.G6ms020.App\Entity\Programme' shared service.
     *
     * @return \App\Entity\Programme
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.G6ms020": it references class "App\\Entity\\Programme" but no such service exists.');
    }
}
