<?php

namespace Container7nU1EQ6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FawmvSYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FawmvSY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FawmvSY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', 'App\\Repository\\ReservationEventRepository', 'getReservationEventRepositoryService', true],
        ], [
            'em' => 'App\\Repository\\ReservationEventRepository',
        ]);
    }
}
