<?php

namespace ContainerSTjdg6O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SwNw0RpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.swNw0Rp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.swNw0Rp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'airport' => ['privates', '.errored..service_locator.swNw0Rp.App\\Entity\\Airport', NULL, 'Cannot autowire service ".service_locator.swNw0Rp": it references class "App\\Entity\\Airport" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'airport' => 'App\\Entity\\Airport',
            'entityManager' => '?',
        ]);
    }
}
