<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E7tHPUbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E7tHPUb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E7tHPUb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'volclass' => ['privates', '.errored..service_locator.E7tHPUb.App\\Entity\\Volclass', NULL, 'Cannot autowire service ".service_locator.E7tHPUb": it references class "App\\Entity\\Volclass" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'volclass' => 'App\\Entity\\Volclass',
        ]);
    }
}
