<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OT2hweMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OT2hweM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OT2hweM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationvol' => ['privates', '.errored..service_locator.OT2hweM.App\\Entity\\Reservationvol', NULL, 'Cannot autowire service ".service_locator.OT2hweM": it references class "App\\Entity\\Reservationvol" but no such service exists.'],
        ], [
            'reservationvol' => 'App\\Entity\\Reservationvol',
        ]);
    }
}
