<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCUtourService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DCUtour' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DCUtour'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ReservationHotelRepository' => ['privates', 'App\\Repository\\ReservationHotelRepository', 'getReservationHotelRepositoryService', true],
            'reservationHotel' => ['privates', '.errored..service_locator.DCUtour.App\\Entity\\ReservationHotel', NULL, 'Cannot autowire service ".service_locator.DCUtour": it references class "App\\Entity\\ReservationHotel" but no such service exists.'],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'ReservationHotelRepository' => 'App\\Repository\\ReservationHotelRepository',
            'reservationHotel' => 'App\\Entity\\ReservationHotel',
            'security' => '?',
        ]);
    }
}
