<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Di5FtErService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Di5FtEr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Di5FtEr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'airportRepository' => ['privates', 'App\\Repository\\AirportRepository', 'getAirportRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'airportRepository' => 'App\\Repository\\AirportRepository',
            'paginator' => '?',
        ]);
    }
}
