<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9BSrmGHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9BSrmGH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9BSrmGH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chambre' => ['privates', '.errored..service_locator.9BSrmGH.App\\Entity\\Chambre', NULL, 'Cannot autowire service ".service_locator.9BSrmGH": it references class "App\\Entity\\Chambre" but no such service exists.'],
        ], [
            'chambre' => 'App\\Entity\\Chambre',
        ]);
    }
}
