<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MRCG20Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mR_CG20' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mR_CG20'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationVoyageRepository' => ['privates', 'App\\Repository\\ReservationVoyageRepository', 'getReservationVoyageRepositoryService', true],
        ], [
            'reservationVoyageRepository' => 'App\\Repository\\ReservationVoyageRepository',
        ]);
    }
}
