<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__2K2fVgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..2K2fVg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..2K2fVg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'programmeRepository' => ['privates', 'App\\Repository\\ProgrammeRepository', 'getProgrammeRepositoryService', true],
        ], [
            'programmeRepository' => 'App\\Repository\\ProgrammeRepository',
        ]);
    }
}
