<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J6M3g5oService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j6M3g5o' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j6M3g5o'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationEventRepository' => ['privates', 'App\\Repository\\ReservationEventRepository', 'getReservationEventRepositoryService', true],
        ], [
            'reservationEventRepository' => 'App\\Repository\\ReservationEventRepository',
        ]);
    }
}
