<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PKiC45TService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pKiC45T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pKiC45T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reservationHotel' => ['privates', '.errored..service_locator.pKiC45T.App\\Entity\\ReservationHotel', NULL, 'Cannot autowire service ".service_locator.pKiC45T": it references class "App\\Entity\\ReservationHotel" but no such service exists.'],
        ], [
            'reservationHotel' => 'App\\Entity\\ReservationHotel',
        ]);
    }
}
