<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UqzLLN_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uqzLLN.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uqzLLN.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'voyage' => ['privates', '.errored..service_locator.uqzLLN..App\\Entity\\Voyage', NULL, 'Cannot autowire service ".service_locator.uqzLLN.": it references class "App\\Entity\\Voyage" but no such service exists.'],
        ], [
            'voyage' => 'App\\Entity\\Voyage',
        ]);
    }
}
