<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HPq2_TrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hPq2.tr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hPq2.tr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'programme' => ['privates', '.errored..service_locator.hPq2.tr.App\\Entity\\Programme', NULL, 'Cannot autowire service ".service_locator.hPq2.tr": it references class "App\\Entity\\Programme" but no such service exists.'],
        ], [
            'programme' => 'App\\Entity\\Programme',
        ]);
    }
}
