<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G6ms020Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G6ms020' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G6ms020'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'programme' => ['privates', '.errored..service_locator.G6ms020.App\\Entity\\Programme', NULL, 'Cannot autowire service ".service_locator.G6ms020": it references class "App\\Entity\\Programme" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'programme' => 'App\\Entity\\Programme',
        ]);
    }
}
