<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChambre2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.ZjRukWG.App\Entity\Chambre' shared service.
     *
     * @return \App\Entity\Chambre
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.ZjRukWG": it references class "App\\Entity\\Chambre" but no such service exists.');
    }
}
