<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHotelService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.TtwMNSj.App\Entity\Hotel' shared service.
     *
     * @return \App\Entity\Hotel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.TtwMNSj": it references class "App\\Entity\\Hotel" but no such service exists.');
    }
}
