<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationHotel2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.UGIhsJA.App\Entity\ReservationHotel' shared service.
     *
     * @return \App\Entity\ReservationHotel
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.UGIhsJA": it references class "App\\Entity\\ReservationHotel" but no such service exists.');
    }
}
