<?php

namespace ContainerUdxx0CV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVoyageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nfO0sN2.App\Entity\Voyage' shared service.
     *
     * @return \App\Entity\Voyage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.nfO0sN2": it references class "App\\Entity\\Voyage" but no such service exists.');
    }
}
