<?php

namespace ContainerFOHOgi2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAirport2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.swNw0Rp.App\Entity\Airport' shared service.
     *
     * @return \App\Entity\Airport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.swNw0Rp": it references class "App\\Entity\\Airport" but no such service exists.');
    }
}
