<?php

namespace ContainerFOHOgi2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVolclass2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E7tHPUb.App\Entity\Volclass' shared service.
     *
     * @return \App\Entity\Volclass
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.E7tHPUb": it references class "App\\Entity\\Volclass" but no such service exists.');
    }
}
