<?php

namespace ContainerKxB9Tok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HHfgZHQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hHfgZHQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hHfgZHQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'volRepository' => ['privates', 'App\\Repository\\VolRepository', 'getVolRepositoryService', true],
        ], [
            'volRepository' => 'App\\Repository\\VolRepository',
        ]);
    }
}
