<?php

namespace ContainerKxB9Tok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAirportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YLnQMhy.App\Entity\Airport' shared service.
     *
     * @return \App\Entity\Airport
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YLnQMhy": it references class "App\\Entity\\Airport" but no such service exists.');
    }
}
