<?php

namespace ContainerKxB9Tok;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getVol2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._zkc3Gn.App\Entity\Vol' shared service.
     *
     * @return \App\Entity\Vol
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._zkc3Gn": it references class "App\\Entity\\Vol" but no such service exists.');
    }
}
