<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2J8x8aG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2J8x8aG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2J8x8aG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2J8x8aG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2J8x8aG\App_KernelDevDebugContainer([
    'container.build_hash' => '2J8x8aG',
    'container.build_id' => '97f369c8',
    'container.build_time' => 1709683675,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2J8x8aG');
