<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSTjdg6O\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSTjdg6O/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSTjdg6O.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSTjdg6O\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSTjdg6O\App_KernelDevDebugContainer([
    'container.build_hash' => 'STjdg6O',
    'container.build_id' => 'a7c47ab3',
    'container.build_time' => 1709746450,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSTjdg6O');
