<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTTjGvTx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTTjGvTx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTTjGvTx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTTjGvTx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTTjGvTx\App_KernelDevDebugContainer([
    'container.build_hash' => 'TTjGvTx',
    'container.build_id' => 'acc7b373',
    'container.build_time' => 1709652944,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTTjGvTx');
